# ------------------------------------------------------------------------
# MixMatchDet
# Copyright (c) 2026 Hochschule Ruhr West
# Licensed under the Apache License, Version 2.0 [See LICENSE for details]
# ------------------------------------------------------------------------

extends: "../3-mixed-candidates/dinov2s_mixed.yml"
run_name: "DINOv2-B__mixed"

wandb:
  group: "DINOv2-B__mixed"
  tags: ["scaling"]

model:
  vit:
    weights: "https://dl.fbaipublicfiles.com/dinov2/dinov2_vitb14/dinov2_vitb14_reg4_pretrain.pth"

    dinov2:
      num_heads: 12
      embed_dim: 768
